python ./save_clips.py 39
python ./save_clips.py 40
python ./save_clips.py 41
python ./save_clips.py 42
python ./save_clips.py 43
python ./save_clips.py 44
python ./save_clips.py 45
python ./save_clips.py 46
python ./save_clips.py 47
