python ./save_clips.py 48
python ./save_clips.py 49
python ./save_clips.py 50
python ./save_clips.py 51
python ./save_clips.py 52
python ./save_clips.py 53
python ./save_clips.py 54
python ./save_clips.py 55
python ./save_clips.py 56
